$ErrorActionPreference = "Stop"

$root = "C:\Users\yildi\Desktop\3Dcad"
$detector = Join-Path $root "src\cad\wall_detector.py"

$stamp = Get-Date -Format "yyyyMMdd_HHmmss"
$backup = Join-Path $root ("backups\wall_continuity_collinear_conflict_" + $stamp)
New-Item -ItemType Directory -Force -Path $backup | Out-Null

if (!(Test-Path $detector)) {
    throw "wall_detector.py not found."
}

Copy-Item $detector (Join-Path $backup "wall_detector.py") -Force

$tmpPy = Join-Path $env:TEMP "wall_continuity_collinear_conflict.py"
[IO.File]::WriteAllBytes($tmpPy, [Convert]::FromBase64String("ZnJvbSBwYXRobGliIGltcG9ydCBQYXRoCgpwYXRoID0gUGF0aChyIkM6XFVzZXJzXHlpbGRpXERlc2t0b3BcM0RjYWRcc3JjXGNhZFx3YWxsX2RldGVjdG9yLnB5IikKdGV4dCA9IHBhdGgucmVhZF90ZXh0KGVuY29kaW5nPSJ1dGYtOCIpCgpyZXF1aXJlZCA9ICgiZGVmIF9zZWdtZW50X2NvbnRhaW5zX3NlZ21lbnQoIiwgImRlZiBfcHJpbWl0aXZlX2VuZHBvaW50X3RvdWNoZXNfc2VsZWN0ZWRfZW5kcG9pbnRzKCIpCmZvciB0b2tlbiBpbiByZXF1aXJlZDoKICAgIGlmIHRva2VuIG5vdCBpbiB0ZXh0OgogICAgICAgIHJhaXNlIFJ1bnRpbWVFcnJvcigiUmVxdWlyZWQgY3VycmVudCB3YWxsIGhlbHBlciBub3QgZm91bmQ6ICIgKyB0b2tlbikKCmhlbHBlcl9hbmNob3IgPSAiZGVmIGRldGVjdF93YWxscyhcbiIKaWYgaGVscGVyX2FuY2hvciBub3QgaW4gdGV4dDoKICAgIHJhaXNlIFJ1bnRpbWVFcnJvcigiZGV0ZWN0X3dhbGxzIGFuY2hvciBub3QgZm91bmQiKQpoZWxwZXIgPSAnZGVmIF9wcmVmZXJyZWRfZW5kcG9pbnRfdG91Y2hpbmdfY29sbGluZWFyX2NhbmRpZGF0ZShcbiAgICBkb2N1bWVudCxcbiAgICBwcmltaXRpdmVfaW5kZXgsXG4gICAgc2VsZWN0ZWRfZW5kcG9pbnRzLFxuICAgIGNsYWltZWRfaW5kaWNlcyxcbiAgICBhbGxvd2VkX2xheWVycyxcbik6XG4gICAgcHJpbWl0aXZlID0gZG9jdW1lbnQucHJpbWl0aXZlc1twcmltaXRpdmVfaW5kZXhdXG4gICAgbGF5ZXIgPSBwcmltaXRpdmVfbGF5ZXIocHJpbWl0aXZlKVxuICAgIG93bl9zZWdtZW50cyA9IHByaW1pdGl2ZV9zZWdtZW50cyhwcmltaXRpdmUpXG5cbiAgICBpZiBub3Qgb3duX3NlZ21lbnRzOlxuICAgICAgICByZXR1cm4gcHJpbWl0aXZlX2luZGV4XG5cbiAgICBiZXN0X2luZGV4ID0gcHJpbWl0aXZlX2luZGV4XG4gICAgYmVzdF9sZW5ndGggPSBtYXgoXG4gICAgICAgIChfc2VnbWVudF9sZW5ndGgoc2VnbWVudCkgZm9yIHNlZ21lbnQgaW4gb3duX3NlZ21lbnRzKSxcbiAgICAgICAgZGVmYXVsdD0wLjAsXG4gICAgKVxuXG4gICAgZm9yIGNhbmRpZGF0ZV9pbmRleCwgY2FuZGlkYXRlIGluIGVudW1lcmF0ZShkb2N1bWVudC5wcmltaXRpdmVzKTpcbiAgICAgICAgaWYgY2FuZGlkYXRlX2luZGV4ID09IHByaW1pdGl2ZV9pbmRleDpcbiAgICAgICAgICAgIGNvbnRpbnVlXG5cbiAgICAgICAgaWYgY2FuZGlkYXRlX2luZGV4IGluIGNsYWltZWRfaW5kaWNlczpcbiAgICAgICAgICAgIGNvbnRpbnVlXG5cbiAgICAgICAgaWYgcHJpbWl0aXZlX2xheWVyKGNhbmRpZGF0ZSkgIT0gbGF5ZXI6XG4gICAgICAgICAgICBjb250aW51ZVxuXG4gICAgICAgIGlmIGxheWVyIG5vdCBpbiBhbGxvd2VkX2xheWVyczpcbiAgICAgICAgICAgIGNvbnRpbnVlXG5cbiAgICAgICAgaWYgbm90IF9wcmltaXRpdmVfZW5kcG9pbnRfdG91Y2hlc19zZWxlY3RlZF9lbmRwb2ludHMoXG4gICAgICAgICAgICBjYW5kaWRhdGUsXG4gICAgICAgICAgICBzZWxlY3RlZF9lbmRwb2ludHMsXG4gICAgICAgICk6XG4gICAgICAgICAgICBjb250aW51ZVxuXG4gICAgICAgIGNhbmRpZGF0ZV9zZWdtZW50cyA9IHByaW1pdGl2ZV9zZWdtZW50cyhjYW5kaWRhdGUpXG5cbiAgICAgICAgaWYgbm90IGNhbmRpZGF0ZV9zZWdtZW50czpcbiAgICAgICAgICAgIGNvbnRpbnVlXG5cbiAgICAgICAgY2FuZGlkYXRlX2NvbnRhaW5zX293biA9IEZhbHNlXG4gICAgICAgIGNhbmRpZGF0ZV9sZW5ndGggPSAwLjBcblxuICAgICAgICBmb3Igb3duX3NlZ21lbnQgaW4gb3duX3NlZ21lbnRzOlxuICAgICAgICAgICAgZm9yIGNhbmRpZGF0ZV9zZWdtZW50IGluIGNhbmRpZGF0ZV9zZWdtZW50czpcbiAgICAgICAgICAgICAgICBpZiBfc2VnbWVudF9jb250YWluc19zZWdtZW50KFxuICAgICAgICAgICAgICAgICAgICBjYW5kaWRhdGVfc2VnbWVudCxcbiAgICAgICAgICAgICAgICAgICAgb3duX3NlZ21lbnQsXG4gICAgICAgICAgICAgICAgKTpcbiAgICAgICAgICAgICAgICAgICAgY2FuZGlkYXRlX2NvbnRhaW5zX293biA9IFRydWVcbiAgICAgICAgICAgICAgICAgICAgY2FuZGlkYXRlX2xlbmd0aCA9IG1heChcbiAgICAgICAgICAgICAgICAgICAgICAgIGNhbmRpZGF0ZV9sZW5ndGgsXG4gICAgICAgICAgICAgICAgICAgICAgICBfc2VnbWVudF9sZW5ndGgoY2FuZGlkYXRlX3NlZ21lbnQpLFxuICAgICAgICAgICAgICAgICAgICApXG5cbiAgICAgICAgaWYgKFxuICAgICAgICAgICAgY2FuZGlkYXRlX2NvbnRhaW5zX293blxuICAgICAgICAgICAgYW5kIGNhbmRpZGF0ZV9sZW5ndGggPiBiZXN0X2xlbmd0aCArIF9FTkRQT0lOVF9UT0xcbiAgICAgICAgKTpcbiAgICAgICAgICAgIGJlc3RfaW5kZXggPSBjYW5kaWRhdGVfaW5kZXhcbiAgICAgICAgICAgIGJlc3RfbGVuZ3RoID0gY2FuZGlkYXRlX2xlbmd0aFxuXG4gICAgcmV0dXJuIGJlc3RfaW5kZXhcblxuXG4nCmlmICJkZWYgX3ByZWZlcnJlZF9lbmRwb2ludF90b3VjaGluZ19jb2xsaW5lYXJfY2FuZGlkYXRlKCIgbm90IGluIHRleHQ6CiAgICB0ZXh0ID0gdGV4dC5yZXBsYWNlKGhlbHBlcl9hbmNob3IsIGhlbHBlciArIGhlbHBlcl9hbmNob3IsIDEpCgpvbGQgPSAnICAgICAgICAgICAgaWYgX3ByaW1pdGl2ZV9lbmRwb2ludF90b3VjaGVzX3NlbGVjdGVkX2VuZHBvaW50cyhcbiAgICAgICAgICAgICAgICBwcmltaXRpdmUsXG4gICAgICAgICAgICAgICAgc2VsZWN0ZWRfZW5kcG9pbnRzLFxuICAgICAgICAgICAgKTpcbiAgICAgICAgICAgICAgICBuZXdseV9zZWxlY3RlZC5hZGQoaW5kZXgpXG4nCm5ldyA9ICcgICAgICAgICAgICBpZiBfcHJpbWl0aXZlX2VuZHBvaW50X3RvdWNoZXNfc2VsZWN0ZWRfZW5kcG9pbnRzKFxuICAgICAgICAgICAgICAgIHByaW1pdGl2ZSxcbiAgICAgICAgICAgICAgICBzZWxlY3RlZF9lbmRwb2ludHMsXG4gICAgICAgICAgICApOlxuICAgICAgICAgICAgICAgIHByZWZlcnJlZF9pbmRleCA9IF9wcmVmZXJyZWRfZW5kcG9pbnRfdG91Y2hpbmdfY29sbGluZWFyX2NhbmRpZGF0ZShcbiAgICAgICAgICAgICAgICAgICAgZG9jdW1lbnQsXG4gICAgICAgICAgICAgICAgICAgIGluZGV4LFxuICAgICAgICAgICAgICAgICAgICBzZWxlY3RlZF9lbmRwb2ludHMsXG4gICAgICAgICAgICAgICAgICAgIGNsYWltZWRfaW5kaWNlcyxcbiAgICAgICAgICAgICAgICAgICAgYWxsb3dlZF9sYXllcnMsXG4gICAgICAgICAgICAgICAgKVxuICAgICAgICAgICAgICAgIG5ld2x5X3NlbGVjdGVkLmFkZChwcmVmZXJyZWRfaW5kZXgpXG4nCmNvdW50ID0gdGV4dC5jb3VudChvbGQpCmlmIGNvdW50IDwgMToKICAgIHJhaXNlIFJ1bnRpbWVFcnJvcigiRW5kcG9pbnQtY29udGludWl0eSBzZWxlY3Rpb24gYmxvY2sgbm90IGZvdW5kIikKdGV4dCA9IHRleHQucmVwbGFjZShvbGQsIG5ldykKCnBhdGgud3JpdGVfdGV4dCh0ZXh0LCBlbmNvZGluZz0idXRmLTgiKQpwcmludCgiQ09OVElOVUlUWS9DT0xMSU5FQVIgQ09ORkxJQ1QgRklYRUQiKQpwcmludCgiVVBEQVRFRCBDT05USU5VSVRZIEJMT0NLUzoiLCBjb3VudCk="))

& py -3.12 $tmpPy

if ($LASTEXITCODE -ne 0) {
    Copy-Item (Join-Path $backup "wall_detector.py") $detector -Force
    throw "Patch failed. Previous wall_detector.py restored."
}

$env:PYTHONPATH = Join-Path $root "src"
$env:PYTHONUTF8 = "1"
$env:PYTHONIOENCODING = "utf-8"

& py -3.12 -m py_compile $detector

if ($LASTEXITCODE -ne 0) {
    Copy-Item (Join-Path $backup "wall_detector.py") $detector -Force
    throw "Compile failed. Previous wall_detector.py restored."
}

& py -3.12 -c "from cad.wall_detector import detect_walls, WallCandidate; print('CONTINUITY COLLINEAR CONFLICT PASS')"

if ($LASTEXITCODE -ne 0) {
    Copy-Item (Join-Path $backup "wall_detector.py") $detector -Force
    throw "Import failed. Previous wall_detector.py restored."
}

Write-Host ""
Write-Host "CONTINUITY / COLLINEAR CONFLICT FIXED" -ForegroundColor Green
Write-Host "When endpoint continuity sees overlapping collinear alternatives, it now prefers the longest candidate that itself touches the selected endpoint network."
Write-Host "Short helper lines are no longer allowed to win merely because they are encountered first."
Write-Host "Existing door, window, layer and final exclusion rules were not changed."
Write-Host ("Backup: " + $backup)
