$ErrorActionPreference = "Stop"

$root = "C:\Users\yildi\Desktop\3Dcad"
$detector = Join-Path $root "src\cad\wall_detector.py"

$stamp = Get-Date -Format "yyyyMMdd_HHmmss"
$backup = Join-Path $root ("backups\wall_fast_overlap_owner_" + $stamp)
New-Item -ItemType Directory -Force -Path $backup | Out-Null

if (!(Test-Path $detector)) {
    throw "wall_detector.py not found."
}

Copy-Item $detector (Join-Path $backup "wall_detector.py") -Force

$tmpPy = Join-Path $env:TEMP "wall_fast_overlap_owner_fix.py"
[IO.File]::WriteAllBytes(
    $tmpPy,
    [Convert]::FromBase64String("ZnJvbSBwYXRobGliIGltcG9ydCBQYXRoCgpwYXRoID0gUGF0aChyIkM6XFVzZXJzXHlpbGRpXERlc2t0b3BcM0RjYWRcc3JjXGNhZFx3YWxsX2RldGVjdG9yLnB5IikKdGV4dCA9IHBhdGgucmVhZF90ZXh0KGVuY29kaW5nPSJ1dGYtOCIpCgppZiAiZGVmIF9idWlsZF9jb2xsaW5lYXJfb3ZlcmxhcF9vd25lcl9tYXAoIiBpbiB0ZXh0OgogICAgcmFpc2UgUnVudGltZUVycm9yKCJGYXN0IG92ZXJsYXAtb3duZXIgZml4IGlzIGFscmVhZHkgaW5zdGFsbGVkIikKCmFuY2hvciA9ICJkZWYgZGV0ZWN0X3dhbGxzKFxuIgppZiBhbmNob3Igbm90IGluIHRleHQ6CiAgICByYWlzZSBSdW50aW1lRXJyb3IoImRldGVjdF93YWxscyBhbmNob3Igbm90IGZvdW5kIikKCmhlbHBlciA9ICdkZWYgX2J1aWxkX2NvbGxpbmVhcl9vdmVybGFwX293bmVyX21hcChkb2N1bWVudCwgY2xhaW1lZF9pbmRpY2VzKTpcbiAgICAjIE9ubHkgc2ltcGxlIDItcG9pbnQgc3RyYWlnaHQgcHJpbWl0aXZlcyBhcmUgY29uc2lkZXJlZC5cbiAgICAjIElmIGEgc2FtZS1sYXllciBsaW5lIGlzIGZ1bGx5IGNvbnRhaW5lZCBpbiBhIGxvbmdlciBjb2xsaW5lYXIgbGluZSxcbiAgICAjIHRoZSBsb25nZXIgbGluZSBiZWNvbWVzIGl0cyB3YWxsLXNlbGVjdGlvbiBvd25lci5cbiAgICByZWNvcmRzX2J5X2xheWVyID0ge31cblxuICAgIGZvciBpbmRleCwgcHJpbWl0aXZlIGluIGVudW1lcmF0ZShkb2N1bWVudC5wcmltaXRpdmVzKTpcbiAgICAgICAgaWYgaW5kZXggaW4gY2xhaW1lZF9pbmRpY2VzOlxuICAgICAgICAgICAgY29udGludWVcblxuICAgICAgICBwb2ludHMgPSB0dXBsZShnZXRhdHRyKHByaW1pdGl2ZSwgInBvaW50cyIsICgpKSBvciAoKSlcbiAgICAgICAgaWYgbGVuKHBvaW50cykgIT0gMjpcbiAgICAgICAgICAgIGNvbnRpbnVlXG5cbiAgICAgICAgc2VnbWVudHMgPSBwcmltaXRpdmVfc2VnbWVudHMocHJpbWl0aXZlKVxuICAgICAgICBpZiBsZW4oc2VnbWVudHMpICE9IDE6XG4gICAgICAgICAgICBjb250aW51ZVxuXG4gICAgICAgIHNlZ21lbnQgPSBzZWdtZW50c1swXVxuICAgICAgICBkaXJlY3Rpb24gPSBfc2VnbWVudF9kaXJlY3Rpb24oc2VnbWVudClcbiAgICAgICAgaWYgZGlyZWN0aW9uIGlzIE5vbmU6XG4gICAgICAgICAgICBjb250aW51ZVxuXG4gICAgICAgIHV4LCB1eSA9IGRpcmVjdGlvblxuICAgICAgICBpZiB1eCA8IC1fRU5EUE9JTlRfVE9MIG9yIChcbiAgICAgICAgICAgIGFicyh1eCkgPD0gX0VORFBPSU5UX1RPTCBhbmQgdXkgPCAtX0VORFBPSU5UX1RPTFxuICAgICAgICApOlxuICAgICAgICAgICAgdXggPSAtdXhcbiAgICAgICAgICAgIHV5ID0gLXV5XG5cbiAgICAgICAgKGF4LCBheSksIChieCwgYnkpID0gc2VnbWVudFxuICAgICAgICBueCwgbnkgPSAtdXksIHV4XG4gICAgICAgIG9mZnNldCA9IGF4ICogbnggKyBheSAqIG55XG5cbiAgICAgICAgIyBRdWFudGl6YXRpb24gaXMgb25seSBmb3IgZ3JvdXBpbmcgbmVhci1pZGVudGljYWwgbGluZXMuXG4gICAgICAgIGtleSA9IChcbiAgICAgICAgICAgIHByaW1pdGl2ZV9sYXllcihwcmltaXRpdmUpLFxuICAgICAgICAgICAgcm91bmQodXgsIDYpLFxuICAgICAgICAgICAgcm91bmQodXksIDYpLFxuICAgICAgICAgICAgcm91bmQob2Zmc2V0LCA2KSxcbiAgICAgICAgKVxuXG4gICAgICAgIHQwID0gYXggKiB1eCArIGF5ICogdXlcbiAgICAgICAgdDEgPSBieCAqIHV4ICsgYnkgKiB1eVxuICAgICAgICBsbywgaGkgPSBzb3J0ZWQoKHQwLCB0MSkpXG5cbiAgICAgICAgcmVjb3Jkc19ieV9sYXllci5zZXRkZWZhdWx0KGtleSwgW10pLmFwcGVuZChcbiAgICAgICAgICAgIChpbmRleCwgbG8sIGhpLCBoaSAtIGxvKVxuICAgICAgICApXG5cbiAgICBvd25lciA9IHt9XG5cbiAgICBmb3IgcmVjb3JkcyBpbiByZWNvcmRzX2J5X2xheWVyLnZhbHVlcygpOlxuICAgICAgICBpZiBsZW4ocmVjb3JkcykgPCAyOlxuICAgICAgICAgICAgY29udGludWVcblxuICAgICAgICAjIExvbmdlc3QgZmlyc3QuIEEgc2hvcnQgbGluZSBjYW4gb25seSBiZSBvd25lZCBieSBhIGxvbmdlciBvbmUuXG4gICAgICAgIHJlY29yZHMgPSBzb3J0ZWQocmVjb3Jkcywga2V5PWxhbWJkYSBpdGVtOiBpdGVtWzNdLCByZXZlcnNlPVRydWUpXG5cbiAgICAgICAgZm9yIHBvcywgKHNob3J0X2luZGV4LCBzaG9ydF9sbywgc2hvcnRfaGksIHNob3J0X2xlbikgaW4gZW51bWVyYXRlKHJlY29yZHMpOlxuICAgICAgICAgICAgYmVzdF9pbmRleCA9IE5vbmVcbiAgICAgICAgICAgIGJlc3RfbGVuID0gc2hvcnRfbGVuXG5cbiAgICAgICAgICAgIGZvciBsb25nX2luZGV4LCBsb25nX2xvLCBsb25nX2hpLCBsb25nX2xlbiBpbiByZWNvcmRzWzpwb3NdOlxuICAgICAgICAgICAgICAgIGlmIGxvbmdfbGVuIDw9IHNob3J0X2xlbiArIF9FTkRQT0lOVF9UT0w6XG4gICAgICAgICAgICAgICAgICAgIGNvbnRpbnVlXG5cbiAgICAgICAgICAgICAgICBpZiAoXG4gICAgICAgICAgICAgICAgICAgIGxvbmdfbG8gPD0gc2hvcnRfbG8gKyBfRU5EUE9JTlRfVE9MXG4gICAgICAgICAgICAgICAgICAgIGFuZCBsb25nX2hpID49IHNob3J0X2hpIC0gX0VORFBPSU5UX1RPTFxuICAgICAgICAgICAgICAgICk6XG4gICAgICAgICAgICAgICAgICAgIGlmIGxvbmdfbGVuID4gYmVzdF9sZW46XG4gICAgICAgICAgICAgICAgICAgICAgICBiZXN0X2luZGV4ID0gbG9uZ19pbmRleFxuICAgICAgICAgICAgICAgICAgICAgICAgYmVzdF9sZW4gPSBsb25nX2xlblxuXG4gICAgICAgICAgICBpZiBiZXN0X2luZGV4IGlzIG5vdCBOb25lOlxuICAgICAgICAgICAgICAgIG93bmVyW3Nob3J0X2luZGV4XSA9IGJlc3RfaW5kZXhcblxuICAgIHJldHVybiBvd25lclxuXG5cbicKdGV4dCA9IHRleHQucmVwbGFjZShhbmNob3IsIGhlbHBlciArIGFuY2hvciwgMSkKCmRldGVjdF9wb3MgPSB0ZXh0LmZpbmQoImRlZiBkZXRlY3Rfd2FsbHMoXG4iKQpoZWFkID0gdGV4dFs6ZGV0ZWN0X3Bvc10KdGFpbCA9IHRleHRbZGV0ZWN0X3BvczpdCgpjbGFpbWVkX2FuY2hvciA9ICIiIiAgICBjbGFpbWVkX2luZGljZXMgPSBzZXQoZG9vcl9pbmRpY2VzKQogICAgY2xhaW1lZF9pbmRpY2VzLnVwZGF0ZSh3aW5kb3dfaW5kaWNlcykKIiIiCmNsYWltZWRfbmV3ID0gIiIiICAgIGNsYWltZWRfaW5kaWNlcyA9IHNldChkb29yX2luZGljZXMpCiAgICBjbGFpbWVkX2luZGljZXMudXBkYXRlKHdpbmRvd19pbmRpY2VzKQoKICAgIG92ZXJsYXBfb3duZXIgPSBfYnVpbGRfY29sbGluZWFyX292ZXJsYXBfb3duZXJfbWFwKAogICAgICAgIGRvY3VtZW50LAogICAgICAgIGNsYWltZWRfaW5kaWNlcywKICAgICkKIiIiCmlmIGNsYWltZWRfYW5jaG9yIG5vdCBpbiB0YWlsOgogICAgcmFpc2UgUnVudGltZUVycm9yKCJjbGFpbWVkX2luZGljZXMgYW5jaG9yIG5vdCBmb3VuZCIpCnRhaWwgPSB0YWlsLnJlcGxhY2UoY2xhaW1lZF9hbmNob3IsIGNsYWltZWRfbmV3LCAxKQoKIyBLVVJBTCAxOiBhZGQgb3duZXIgaW5zdGVhZCBvZiB0aGUgc2hvcnRlciBjb250YWluZWQgbGluZS4Kb2xkID0gIiIiICAgICAgICAgICAgc2VsZWN0ZWRfaW5kaWNlcy5hZGQoaW5kZXgpCiAgICAgICAgICAgIGFsbG93ZWRfbGF5ZXJzLmFkZCgKICAgICAgICAgICAgICAgIHByaW1pdGl2ZV9sYXllcihwcmltaXRpdmUpCiAgICAgICAgICAgICkKIiIiCm5ldyA9ICIiIiAgICAgICAgICAgIHNlbGVjdGVkX2luZGV4ID0gb3ZlcmxhcF9vd25lci5nZXQoaW5kZXgsIGluZGV4KQogICAgICAgICAgICBzZWxlY3RlZF9pbmRpY2VzLmFkZChzZWxlY3RlZF9pbmRleCkKICAgICAgICAgICAgYWxsb3dlZF9sYXllcnMuYWRkKAogICAgICAgICAgICAgICAgcHJpbWl0aXZlX2xheWVyKGRvY3VtZW50LnByaW1pdGl2ZXNbc2VsZWN0ZWRfaW5kZXhdKQogICAgICAgICAgICApCiIiIgppZiBvbGQgbm90IGluIHRhaWw6CiAgICByYWlzZSBSdW50aW1lRXJyb3IoIlJ1bGUgMSBzZWxlY3Rpb24gYW5jaG9yIG5vdCBmb3VuZCIpCnRhaWwgPSB0YWlsLnJlcGxhY2Uob2xkLCBuZXcsIDEpCgojIEtVUkFMIDI6IGFkZCBvd25lciBpbnN0ZWFkIG9mIHRoZSBzaG9ydGVyIGNvbnRhaW5lZCBsaW5lLgpvbGQgPSAiIiIgICAgICAgICAgICAgICAgc2VsZWN0ZWRfaW5kaWNlcy5hZGQoaW5kZXgpCiIiIgpuZXcgPSAiIiIgICAgICAgICAgICAgICAgc2VsZWN0ZWRfaW5kaWNlcy5hZGQoCiAgICAgICAgICAgICAgICAgICAgb3ZlcmxhcF9vd25lci5nZXQoaW5kZXgsIGluZGV4KQogICAgICAgICAgICAgICAgKQoiIiIKaWYgb2xkIG5vdCBpbiB0YWlsOgogICAgcmFpc2UgUnVudGltZUVycm9yKCJSdWxlIDIgc2VsZWN0aW9uIGFuY2hvciBub3QgZm91bmQiKQp0YWlsID0gdGFpbC5yZXBsYWNlKG9sZCwgbmV3LCAxKQoKIyBFdmVyeSBlbmRwb2ludC1jb250aW51aXR5IGJhdGNoOiB3aGVuIGEgc2hvcnQgY29udGFpbmVkIGxpbmUgaXMgdGhlIG9uZQojIHRoYXQgdG91Y2hlcyB0aGUgbmV0d29yaywgYWRkIGl0cyBwcmVjb21wdXRlZCBsb25nZXIgb3duZXIgaW5zdGVhZC4Kb2xkID0gIiIiICAgICAgICAgICAgICAgIG5ld2x5X3NlbGVjdGVkLmFkZChpbmRleCkKIiIiCm5ldyA9ICIiIiAgICAgICAgICAgICAgICBuZXdseV9zZWxlY3RlZC5hZGQoCiAgICAgICAgICAgICAgICAgICAgb3ZlcmxhcF9vd25lci5nZXQoaW5kZXgsIGluZGV4KQogICAgICAgICAgICAgICAgKQoiIiIKY291bnQgPSB0YWlsLmNvdW50KG9sZCkKaWYgY291bnQgPCAxOgogICAgcmFpc2UgUnVudGltZUVycm9yKCJFbmRwb2ludCBjb250aW51aXR5IHNlbGVjdGlvbiBhbmNob3Igbm90IGZvdW5kIikKdGFpbCA9IHRhaWwucmVwbGFjZShvbGQsIG5ldykKCiMgQm90aC1lbmRwb2ludCBydWxlLCBpZiBwcmVzZW50LgpvbGQgPSAiIiIgICAgICAgICAgICBib3RoX2VuZHBvaW50X2luZGljZXMuYWRkKGluZGV4KQoiIiIKbmV3ID0gIiIiICAgICAgICAgICAgYm90aF9lbmRwb2ludF9pbmRpY2VzLmFkZCgKICAgICAgICAgICAgICAgIG92ZXJsYXBfb3duZXIuZ2V0KGluZGV4LCBpbmRleCkKICAgICAgICAgICAgKQoiIiIKaWYgb2xkIGluIHRhaWw6CiAgICB0YWlsID0gdGFpbC5yZXBsYWNlKG9sZCwgbmV3KQoKdGV4dCA9IGhlYWQgKyB0YWlsCnBhdGgud3JpdGVfdGV4dCh0ZXh0LCBlbmNvZGluZz0idXRmLTgiKQoKcHJpbnQoIkZBU1QgT1ZFUkxBUCBPV05FUiBGSVggQVBQTElFRCIpCnByaW50KCJFTkRQT0lOVCBCTE9DS1MgVVBEQVRFRDoiLCBjb3VudCkK")
)

& py -3.12 $tmpPy

if ($LASTEXITCODE -ne 0) {
    Copy-Item (Join-Path $backup "wall_detector.py") $detector -Force
    throw "Patch failed. Previous wall_detector.py restored."
}

$env:PYTHONPATH = Join-Path $root "src"
$env:PYTHONUTF8 = "1"
$env:PYTHONIOENCODING = "utf-8"

& py -3.12 -m py_compile $detector

if ($LASTEXITCODE -ne 0) {
    Copy-Item (Join-Path $backup "wall_detector.py") $detector -Force
    throw "Compile failed. Previous wall_detector.py restored."
}

& py -3.12 -c "from cad.wall_detector import detect_walls, WallCandidate; print('FAST OVERLAP OWNER PASS')"

if ($LASTEXITCODE -ne 0) {
    Copy-Item (Join-Path $backup "wall_detector.py") $detector -Force
    throw "Import failed. Previous wall_detector.py restored."
}

Write-Host ""
Write-Host "FAST OVERLAP OWNER FIX INSTALLED" -ForegroundColor Green
Write-Host "Only exact same-layer collinear contained 2-point lines are handled."
Write-Host "The shorter overlapping line cannot own wall continuity; its longer containing line is selected instead."
Write-Host "The overlap map is calculated once, so the previous repeated full-drawing scan is not used."
Write-Host "Existing door, window, layer and exclusion rules remain unchanged."
Write-Host ("Backup: " + $backup)
